### PR TITLE
Tim vignette edits

### LINKED ISSUE #200: Vignette: add the two png images in vignette/images to the Rmd and describe output

### PR DESCRIPTION
**Pull request by tjthurman**
This PR contains pretty extensive edits to the vignette to flesh it out into a detailed tutorial. It moves some files around to get things right with R CMD check and make sure users can use the example data files we provide, and it adds in the images to fix #200 .

### CODE REVIEW

**Review by ByrumLab — COMMENTED** [review]
line 112. We can remove the language about the Pool samples. Most projects will not have a pool. It is simply an example group to show how to remove a group in the example. A pool of all samples in the experiment. 

line 135. This is incorrect. NA and 0s both mean we do not know if the protein is there or not. It is simply undetected. The difference is in how limma calculates the fold change. If they are NA, the NA.omit is used and it is not part of the fold change. If they are zero, then it is included and changes the fold change.

**Review by ByrumLab — COMMENTED** [review]
line 137. remove because it was below the detection limit. There are many reasons it may have not been detected. It is not always the lowest abundant proteins.

**Comment by tjthurman** [comment]
OK, made edits in response to these comments. I cleaned up lines 112 and 137. I tried to clarify line 135 more: from the point of view of the limma models, a 0 is saying that we know the protein is not present (it is including 0 in the logFC calculations). So I tried to re-write it to make it clearer: the in the "model world" a 0 is treated as if we know the protein is not present, but in the "real world"  this is rarely the case, so we shouldn't use 0s unless we're sure.

**Comment by tjthurman** [comment]
OK, a little more clarification that is hopefully correct!

**Review by ByrumLab — APPROVED** [review]

**Pull request merged**
